function [fitresult, gof] = createFit(Resilient_Backpropagation, Firefly)
%CREATEFIT(RESILIENT_BACKPROPAGATION,FIREFLY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Resilient_Backpropagation
%      Y Output: Firefly
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jul-2022 17:34:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Resilient_Backpropagation, Firefly );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData,'linewidth',2,'MarkerFaceColor',[0.1,0.9,0.1]);
% h.linewidth=3;
legend( h, 'Firefly vs. Resilient_Backpropagation', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Resilient_Backpropagation', 'Interpreter', 'none' );
ylabel( 'Firefly', 'Interpreter', 'none' );
grid on


